[package]
name = "xmlman"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
clap = { version = "4.5.46", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
rhai = "1.22.2"
xml-rs = "1.0.0"
xmlparser = "0.13.6"
